### ISSUE TITLE
Fail to get correct result from king (Step 1) for the case of whole chromosome

### ISSUE THREAD

**Issue by lxwgcool** [rounakdey/FastSparseGRM#8] opened 2023-07-13 19:47 UTC
This ticket is related to the previous ticket (the link below), which has been closed 
https://github.com/rounakdey/FastSparseGRM/issues/7

Dear Rounak,

As I described in the previous ticket (mentioned above), the king could process the single chromosome (e.g., chr1) successfully. However, it failed to process the case of whole chromosome.  Since the STAARpipeline requires the GRM file that based on the whole chromosome, I have to use the king to process the whole chromosome case in step 1 to generate the correct "output.king.seg". 

Previously, you suggest me to remove chromosome X and Y from the original vcf file before use plink to convert it to bed file. I did many testing today, including remove the chrX and chrY related lines in vcf header.  Plink could always convert the vcf to bed file successfully. However, the king keeps giving us nothing. Please check the attachment below.

[AllChrom.tar.gz](https://github.com/rounakdey/FastSparseGRM/files/12043925/AllChrom.tar.gz)

So right now I stuck again. Please help.
Best
Xin

**Comment by rounakdey** [comment] 2023-07-21 05:28
This is indeed a very unexpected problem. I do not see anything wrong with your KING job submission or anything. Can you try using KING --kinship instead of --ibdseg to see if it finds any related pairs?

**Comment by lxwgcool** [comment] 2023-08-17 13:21
Thanks Rounak, 
I can successfully get the results by using --kinship. I will use it to process the remaining steps. 
I will update this ticket once everything is all set or if there are still some issue. 
Thanks again
Best
Xin

**Comment by lxwgcool** [comment] 2023-08-17 15:16
Hi Rounak, 

Good news! I have successfully generated the sGRM files after using "KING --kinship instead of --ibdseg" in step 2. 

I will use this sGRM to run the remaining steps of STAARPipeline. 

Thanks so much again for your help.
Best
Xin

**Comment by rounakdey** [comment] 2023-09-27 15:30
I am closing this issue since you mentioned the issue is resolved.

**Closed as completed by rounakdey** 2023-09-27 15:30 UTC
