### ISSUE TITLE
Help Needed with FastSparseGRM Pipeline Execution

### ISSUE THREAD

**Issue by mzw-jyz** [rounakdey/FastSparseGRM#15] opened 2024-11-30 05:31 UTC
Dear rounakdey,

I am currently using the FastSparseGRM pipeline and ran into an issue during the first step, Run KING. When executing this step, I encountered an error, and I’m unsure about the cause. Below is the log from the execution:(myenv) [mozhiwen@PRD mozhiwen]$ /md3800f/file/Grade2024/mozhiwen/FastSparseGRM/extdata/king -b /md3800f/file/Grade2024/mozhiwen/mt-staar/56_merge_6/chrall.bed --ibdseg --degree 4 --cpus 4 --prefix output.kingKING 2.3.2 - (c) 2010-2023 Wei-Min Chen

The following parameters are in effect:
                   Binary File : /md3800f/file/Grade2024/mozhiwen/mt-staar/56_merge_6/chrall.bed (-bname)

Additional Options
         Close Relative Inference : --related, --duplicate
   Pairwise Relatedness Inference : --kinship, --ibdseg [ON], --ibs, --makeGRM
              Inference Parameter : --degree [4], --noscreen, --seglength,
                                    --minConc [0.80]
         Relationship Application : --unrelated, --cluster, --build
                        QC Report : --bysample, --bySNP, --roh, --autoQC
                     QC Parameter : --callrateN, --callrateM
             Population Structure : --pca, --mds
              Structure Parameter : --projection, --pcs
          Quantitative Trait GWAS : --lmm
                Binary Trait GWAS : --tdt, --gdt
                Association Model : --trait [], --covariate [], --maxP
     Association Method Parameter : --invnorm
               Genetic Risk Score : --risk, --model [], --prevalence, --noflip
              Computing Parameter : --cpus [4]
                   Optional Input : --fam [], --bim [], --phefile [],
                                    --covfile [], --prunedsnp [],
                                    --sexchr [23]
                           Output : --rplot, --pngplot, --plink
                 Output Parameter : --prefix [output.king], --rpath []

KING starts at Sat Nov 30 19:34:36 2024
Loading genotype data in PLINK binary format...
Read in PLINK fam file /md3800f/file/Grade2024/mozhiwen/mt-staar/56_merge_6/chrall.fam...

FATAL ERROR - 
Incorrect formating for affection status Col 0, Affection DISEASEKING
Family: 00003  Individual: 00003  Status: 3

(myenv) [mozhiwen@PRD mozhiwen]$ head /md3800f/file/Grade2024/mozhiwen/mt-staar/56_merge_6/chrall.fam
00003 00003 0 0 0 3.9208
00006 00006 0 0 0 3.96695
00007 00007 0 0 0 3.09354
00012 00012 0 0 0 3.44967
00022 00022 0 0 0 3.14721
00024 00024 0 0 0 4.018
00025 00025 0 0 0 3.98854
00033 00033 0 0 0 3.76811
00035 00035 0 0 0 3.76403
00041 00041 0 0 0 3.34537
In my fam file, the 6th column contains melatonin concentration data, which is a continuous variable. Could this be causing the issue? Is KING unable to handle continuous variables, or is there another problem I should address?
I would greatly appreciate your insights on this matter and any advice you could offer for resolving the issue.
Thank you!

**Comment by rounakdey** [comment] 2024-11-30 06:08
Yes, it seems the problem is with the 6th column. You can try replacing all values in the 6th column with `-9` (which represents "missing") and then run KING.

**Comment by mzw-jyz** [comment] 2024-11-30 07:07
Thank you for your quick response and suggestion. Following your advice, I replaced all values in the 6th column with -9 to represent "missing" data, and I run KING again. I'm happy to report that the process was successful!Thank you once again for your time and support!

**Comment by rounakdey** [comment] 2024-11-30 07:22
No problem. Please raise an issue (or reopen this one) if you get stuck at a subsequent steps. Closing this issue for now.

**Closed as completed by rounakdey** 2024-11-30 07:22 UTC
